pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Cypress Tests') {
            steps {
                sh './node_modules/.bin/cypress run --headless'
            }
        }

        stage('Generate Cucumber HTML Report') {
            steps {
                // Generate the HTML report from the JSON file generated by Cypress
                sh 'npx cucumber-html-reporter --jsonFile=cypress/results/results.json --reportFile=cypress/results/cucumber_report.html'
            }
        }

        stage('Publish Test Results') {
            steps {
                // Publish Cucumber report as an artifact
                archiveArtifacts artifacts: 'cypress/results/cucumber_report.html', allowEmptyArchive: true
            }
        }

        stage('Clean Up') {
            steps {
                echo 'Cleaning up...'
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
