export enum Checkout {
  BACKPACK_CART_BUTTON = '[data-test="add-to-cart-sauce-labs-backpack"]',
  BIKELIGHT_CART_BUTTON = '[data-test="add-to-cart-sauce-labs-bike-light"]',
  BOLTTSHIRT_CART_BUTTON = '[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]',
  FLEECEJACKET_CART_BUTTON = '[data-test="add-to-cart-sauce-labs-fleece-jacket"]',
  ONESIE_CART_BUTTON = '[data-test="add-to-cart-sauce-labs-onesie"]',
  REDTSHIRT_CART_BUTTON = '[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]',
  ITEM_PRICE_DIV = '[data-test="inventory-item-price"]',
  ADD_TO_CART_BUTTON = 'Add to cart',
  REMOVE_BUTTON = 'Remove',
  REMOVE_BACKPACK_BUTTON = '[data-test="remove-sauce-labs-backpack"]',
  REMOVE_BIKELIGHT_BUTTON = '[data-test="remove-sauce-labs-bike-light"]',
  REMOVE_BOLTTSHIRT_BUTTON = '[data-test="remove-sauce-labs-bolt-t-shirt"]',
  REMOVE_FLEECEJACKET_BUTTON = '[data-test="remove-sauce-labs-fleece-jacket"]',
  REMOVE_ONESIE_BUTTON = '[data-test="remove-sauce-labs-onesie"]',
  REMOVE_REDTSHIRT_BUTTON = '[data-test="remove-test.allthethings()-t-shirt-(red)"]',
  CART_ICON = '[data-test="shopping-cart-link"]',
  CART_AMOUNT = '[data-test="shopping-cart-badge"]',
  CONTINUE_SHOPPING_BUTTON = '[data-test="continue-shopping"]',
  CHECKOUT_BUTTON = '[data-test="checkout"]',
  FIRST_NAME_TXTBOX = '[data-test="firstName"]',
  LAST_NAME_TXTBOX = '[data-test="lastName"]',
  POSTAL_CODE_TXTBOX = '[data-test="postalCode"]',
  FIRST_NAME_ERROR = 'Error: First Name is required',
  LAST_NAME_ERROR = 'Error: Last Name is required',
  POSTAL_CODE_ERROR = 'Error: Postal Code is required',
  CONTINUE_BUTTON = '#continue',
  CANCEL_BUTTON = '[data-test="cancel"]',
  FINISH_BUTTON = '[data-test="finish"]',
  BACK_TO_PRODUCTS_BUTTON = '[data-test="back-to-products"]',
  PAYMENT_INFO = '[data-test="payment-info-value"]',
  SHIPPING_INFO = '[data-test="shipping-info-value"]',
  SUBTOTAL_DIV = '[data-test="subtotal-label"]',
  TAXES_DIV = '[data-test="tax-label"]',
  TOTAL_DIV = '[data-test="total-label"]',
  CART_LIST_DIV = '[data-test="cart-list"]',
  CART_ITEMS = '[data-test="inventory-item"]',
}
